### ISSUE TITLE
Carlels Review

### ISSUE THREAD

**Issue by inesrob** [roll-wg/draft-rnfd#4]
Link to the Review: https://mailarchive.ietf.org/arch/msg/roll/laGVKMMY9jt_O_4yJfZ9g97ykeM/

**Comment by konrad-iwanicki** [comment]
Comments addressed in revision 03.

To be addressed is a comment regarding the 0.12 threshold.

**Comment by konrad-iwanicki** [comment]
Just addressed the remaining comment.
